name: "Build and test"
on: push
jobs:
    build-and-test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v17
              with:
                  extra_nix_config: |
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            - run: nix build .#"casper:lib:casper"
            - run: nix build .#"casper:test:casper-spec"
